### ISSUE TITLE
size_t while deserializing and int in serialization, size mismatch.

### ISSUE THREAD

**Issue by hjeldin** [cubase01/Serialization#1]
Hi,
we spent a good hour trying to understand why on our x86_64 machine the serialized data was 4 bytes shorter.

We traced back the issue to serialization.cpp on lines 67/76/86 and 106/114/122/130.  
A workaround can be serializing the size as uint32_t or any other fixed size, architecture-independent type.

Bye,
Riccardo.

**Comment by zk4** [comment]
done,thanks for pointing out :)
