### ISSUE TITLE
Idea for support std::vector<MyClass> instead using MyClass*

### ISSUE THREAD

**Issue by nicolapiccinelli** [cubase01/Serialization#2]
Hey,
after spending a few hours trying to serialize vector of a custom structure i found a possible solution to support the serialization of this type of data. The idea is to add two new functions for serialize vector with two templates for cast the container content to ISerializable\* for drive the call to the serialization function for the ISerialization\* type. That's the code

```
template <typename CastType, class T>
static std::ostream& Serialize(std::ostream& ostream_, std::vector<T>& container)
{
    uint32_t size = container.size();
    Serialize(ostream_, size);
    for (auto& ite : container)
    {
        Serialize(ostream_, (CastType*) &ite);
    }
    return ostream_;
}

template <typename CastType, class T>
static std::istream& DeSerialize(std::istream& istream_, std::vector<T>&container)
{
    if (!istream_.good() || istream_.eof())return istream_;

    int size;
    container.clear();
    DeSerialize(istream_, size);
    for (int i = 0; i < size; ++i)
    {
        T t;
        DeSerialize(istream_, (CastType*) &t);
        container.push_back(  t);
    }
    assert(istream_.good());
    return istream_;
}
```

and then you can serialize calling:

```
serialize::Serialize<ISerializable,MyClass>(outbuf, object);
```

**Comment by vkhandus** [comment]
Ciao, few months ago I wrote some code using serialization idea described in this repo.
My approach supports serialization of some STL containers.

Look here:
https://github.com/vkhandus/cpp-serialization

**Comment by zk4** [comment]
open for pr~

**Comment by zk4** [comment]
already support .check that out :)
